[profile.default]
src = "src"
out = "out"
libs = ["lib"]

eth-rpc-url = "https://sepolia.infura.io/v3/0991b5584f77456b88fbdf29732ecbfb"
remappings = [
    '@chainlink-brownie-contracts/=lib/chainlink-brownie-contracts/',
    '@chainlink/=lib/chainlink/',
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
